@HostAddress = https://api.openweathermap.org
@apiKey = {{OpenWeatherMapApiKey}}

# city location
@lat=51.5073219
@lon=-0.1276474

### location of a city

GET {{HostAddress}}/geo/1.0/direct?q=London&limit=10&appid={{apiKey}}
Accept: application/json


### current weather data


GET {{HostAddress}}/data/2.5/weather?lat={{lat}}&lon={{lon}}&exclude=minutely,hourly&units=metric&appid={{apiKey}}
Accept: application/json


### 5 days weather forecast


GET {{HostAddress}}/data/2.5/forecast?lat={{lat}}&lon={{lon}}&units=metric&appid={{apiKey}}
Accept: application/json