@HostAddress = https://api.openweathermap.org
@apiKey = xxx

GET {{HostAddress}}/geo/1.0/direct?q=London&limit=1&appid={{apiKey}}
Accept: application/json

###

@lat=51.5073219
@lon=-0.1276474

GET {{HostAddress}}/data/2.5/weather?lat={{lat}}&lon={{lon}}&exclude=minutely,hourly&appid={{apiKey}}
Accept: application/json
